language: c

sudo: false

compiler:
   - gcc
   - clang

env:
   matrix:
      - S=static-init
      - S=init
      - S=overlay
      - S=standalone
      - S=shellfunc

script:
   -  cd ${S##*-};
   -  (
         case "${S}" in
            static-*)  make STATIC=1 || exit ;;
            *)         make STATIC=0 || exit ;;
         esac;
      )
   -  (
         case "${S}" in
            init)         size build/lib/* build/bin/*  || exit ;;
            static-init)  size build/bin/*              || exit ;;
            *standalone)  du -B 1K build/boot.cpio*     || exit ;;
         esac;
      )
