#include $(SRCDIR)/app/aufs-overlayfs-wrapper/obj_defs.mk
include $(SRCDIR)/app/create-user-tmpdirs/obj_defs.mk
include $(SRCDIR)/app/ztmpfs/obj_defs.mk
include $(SRCDIR)/app/pingloop/obj_defs.mk
include $(SRCDIR)/app/untar/obj_defs.mk
include $(SRCDIR)/app/filescan/obj_defs.mk
include $(SRCDIR)/app/filesize/obj_defs.mk
include $(SRCDIR)/app/read-proc/obj_defs.mk
include $(SRCDIR)/app/ssh-validate-sync-command/obj_defs.mk
