$(eval $(call C_LIB_DEF,fischstaebchen,COMMON ZRAM))
LIBFISCHSTAEBCHEN_STD_DEP           = $(OLIB)/$(LIBFISCHSTAEBCHEN_SO_FILENAME)
LIBFISCHSTAEBCHEN_STD_INCLUDE       = fischstaebchen

#$(eval $(call C_LIB_DEF,fischstaebchen_initramfs,COMMON ZRAM INITRAMFS))
#LIBFISCHSTAEBCHEN_INITRAMFS_DEP     = $(OLIB)/$(LIBFISCHSTAEBCHEN_INITRAMFS_SO_FILENAME)
#LIBFISCHSTAEBCHEN_INITRAMFS_INCLUDE = fischstaebchen_initramfs


LIBFISCHSTAEBCHEN_ANY_DEP     = $(LIBFISCHSTAEBCHEN_STD_DEP)
LIBFISCHSTAEBCHEN_ANY_INCLUDE = $(LIBFISCHSTAEBCHEN_STD_INCLUDE)
